[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
excluded-patches = "'GmsCore support'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "20.12.46"
excluded-patches = "'Disable rolling number animations' 'GmsCore support'"

